### ISSUE TITLE
nothing happens when i run ./run-platform.sh

### ISSUE THREAD

**Issue by legaltextai** [Zipstack/unstract#342]
ubuntu, server. git cloned. but i get no notification that any processes started after i run this command. do i need to start docker first?

**Comment by hari-kuriakose** [comment]
@legaltextai The `run-platform.sh` script directs all log messages to stdout and therefore will be visible as the command output.

And yes, docker daemon should be running already. However the script will internally check if docker is available and throw error messages with suggestive actions otherwise.

If you are still facing any issues, could you please share a screenshot of the `run-platform.sh` script output in the terminal?

**Comment by ritwik-g** [comment]
@legaltextai please let us know if the issue got solved.
