### ISSUE TITLE
fix: [ISSUE]

### ISSUE THREAD

**Issue by taka4884** [Zipstack/unstract#586]
## To reproduce
Steps to reproduce the behavior.

## Environment details
 - Version: [e.g. 0.41.2]

**Comment by Deepak-Kesavan** [comment]
Hi @taka4884,

Thank you for reaching out. It appears that this issue was created using the default template without any additional details provided. If this was unintentional, I'll proceed to close the issue.

However, if there is a specific bug or concern related to Unstract that you intended to report, please feel free to reopen this issue or create a new one with the relevant details. We're here to assist you with any challenges you might be facing.

Thank you for your understanding!
